name: hearthstone_api
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  flutter: '>=3.10.0 <4.0.0'
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Pub.dev packages.
  alice_lightweight: ^3.4.0
  auto_route: ^7.4.0
  cached_network_image: ^3.2.3
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.0
  json_annotation: ^4.8.1
  responsive_builder: ^0.7.0
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  styled_widget: ^0.4.1
  supabase_auth_ui: ^0.2.0
  supabase_flutter: ^1.10.4
  supercharged: ^2.1.1
  visibility_detector: ^0.4.0+2
  flutter_hooks: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  freezed: ^2.3.4

flutter:
  uses-material-design: true
